In [3]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

1.Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [4]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [5]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [6]:
np.random.uniform(-1, 1, (5, 5))

array([[-0.53850328,  0.4903643 , -0.67922073, -0.23741909,  0.10493187],
       [-0.05328483,  0.21638016,  0.70970891,  0.26887066,  0.24724465],
       [ 0.83098277,  0.06899512, -0.40449962, -0.26135494, -0.21323644],
       [ 0.34440088, -0.81265975, -0.16482608, -0.08297666, -0.28011327],
       [ 0.35942483,  0.14343256, -0.0913175 ,  0.97866266,  0.92732847]])

Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [7]:
np.random.uniform(0,1,(3,3))

array([[0.06533543, 0.75480308, 0.70024293],
       [0.72884539, 0.72051318, 0.94617413],
       [0.57225656, 0.02423499, 0.58895495]])

Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення

In [8]:
vector_1 = np.random.randint(1, 21, 6)

In [9]:
vector_2 =np.random.randint(1, 21, 6)

In [10]:
vector_1 + vector_2

array([27,  8,  9, 21, 21, 12])

In [11]:
vector_1 - vector_2

array([ -5,  -2,   5, -13,  -9,  -6])

In [12]:
vector_1 * vector_2

array([176,  15,  14,  68,  90,  27])

Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [13]:
matr_1 = np.random.randint(1,6,(3,2))

In [14]:
matr_2 = np.random.randint(1,6,(2,4))

In [15]:
np.dot(matr_1,matr_2)

array([[15,  4, 19,  4],
       [35, 10, 45, 10],
       [ 7,  2,  9,  2]])

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [16]:
transposed_matrix = np.random.uniform(0,1, (3,3))

In [17]:
np.transpose(transposed_matrix)

array([[0.1104079 , 0.16553385, 0.96099591],
       [0.43803624, 0.567092  , 0.61386368],
       [0.42121611, 0.92760514, 0.25536909]])

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [18]:
first_matrix = np.random.randint(1,11,(3,3))

In [19]:
second_matrix = np.random.randint(1,11,(3,3))

In [20]:
first_matrix - second_matrix

array([[ 3,  1,  3],
       [-4,  1,  1],
       [-8,  0,  2]])

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [21]:
np.random.randint(-5,5, (3,3)) * np.random.randint(-5,5, (3,3))

array([[ 15, -10,  -8],
       [ 12,  -6,  -8],
       [  1,   3,   4]])

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [22]:
matrix = np.random.uniform(-1, 1, (3, 3))

In [23]:
np.sum(matrix, axis=1)

array([ 1.30172227,  2.36841653, -0.2160462 ])

# За допомогою метода  read_html  скачати дані з  таблиці "Коефіцієнт народжуваності в регіонах України (1950—2014)" за посиланням  

# Відобразити перші 10 рядків таблиці за допомогою методу head

In [24]:
df = pd.read_html('https://uk.wikipedia.org/wiki/%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%B6%D1%83%D0%B2%D0%B0%D0%BD%D1%96%D1%81%D1%82%D1%8C_%D0%B2_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%96')

In [25]:
df = df[20]

In [26]:
df.head(10)

регіон   1950   1960   1970  1990  1992  1994  1996  \
0  Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1          Вінницька область  224.0  192.0  142.0   124   119   107   103   
2          Волинська область  247.0  250.0  179.0   153   150   137   125   
3   Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4           Донецька область  271.0  214.0  140.0   109    94    82    70   
5        Житомирська область  261.0  223.0  159.0   129   128   118   108   
6       Закарпатська область  314.0  273.0  207.0   168   161   138   128   
7         Запорізька область  219.0  197.0  150.0   124   107    92    81   
8  Івано-Франківська область  243.0  248.0  182.0   155   144   131   122   
9           Київська область  204.0  189.0  156.0   123   111    99    92   

   2000  2004  2008  2012   2014  
0    73    90   119   126    NaN  
1    84    90   108   112  109.0  
2   112   119   148   148  141.0  
3    71    89   110   112  111.0  
4    61    76    98    98   82.0  
5    89    98   113   122  120.0  
6   115   124   147   151  146.0  
7    71    85   103   106  106.0  
8   103   107   123   124  122.0  
9    73    90   117   122  121.0

# Визначити кількість рядків і стовпців в датафрейме (метод shape)

In [27]:
df.shape

(28, 13)

In [28]:
df.dtypes

регіон     object
1950      float64
1960      float64
1970      float64
1990        int64
1992        int64
1994        int64
1996        int64
2000        int64
2004        int64
2008        int64
2012        int64
2014      float64
dtype: object

# Замініть значення "—" в таблиці значеннями NaN

In [29]:
# ми можемо побачити, що NaN розставлені автоматично замість -

In [30]:
df.astype({'1950':np.float}).head()

<ipython-input-30-9575297a5e6f>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df.astype({'1950':np.float}).head()


регіон   1950   1960   1970  1990  1992  1994  1996  \
0  Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1          Вінницька область  224.0  192.0  142.0   124   119   107   103   
2          Волинська область  247.0  250.0  179.0   153   150   137   125   
3   Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4           Донецька область  271.0  214.0  140.0   109    94    82    70   

   2000  2004  2008  2012   2014  
0    73    90   119   126    NaN  
1    84    90   108   112  109.0  
2   112   119   148   148  141.0  
3    71    89   110   112  111.0  
4    61    76    98    98   82.0

In [31]:
ми можемо побачити в датафреймі немає строкових типів даних, вони float aбо int

SyntaxError: ignored

# Обчислити, скільки проміжків у кожному стовпці (використовуйте методи isnull, sum та len)

In [ ]:
df.isnull().sum()

In [ ]:
df

# Видалити дані для всієї країни з таблиці в останньому рядку таблиці

In [ ]:
df.reset_index(drop=True)

In [ ]:
df.drop(index = 27, inplace=True)

In [ ]:
df.shape

# Замінити пропущені дані у стовпцях середніми значеннями за стовпчиком  (метод fillna)

In [ ]:
df.fillna(df.mean(), inplace=True)

In [ ]:
df.head()

In [ ]:
df

In [ ]:
df
df.fillna(df.mean(), inplace=True)

In [ ]:
df.drop(index=27, inplace = True)

# Отримайте список регіонів, де народжуваність у 2014 році була вищою за середню по Україні

In [ ]:
avg = df['2014'].mean()

In [ ]:
df[df['2014'] > avg]

In [ ]:
df[df['2014'] > med]

# В якому регіоні була найвища народжуваність у 2010 та 2012 роках (окремо).

In [ ]:
df[['регіон','2012']].groupby('регіон').agg({'2012':'sum'}).sort_values('2012',ascending = False).head()

In [ ]:
top_2014 = data = df[['регіон','2014']].sort_values('2014',ascending = False)

In [ ]:
top_2014

# Побудуйте стовпчасту народжуваності за регіонами у 2014 році

In [ ]:
plt.figure(figsize=(10,5))
sns.barplot(data = top_2014, x = top_2014['регіон'], y = top_2014['2014'])
plt.xticks(rotation=90)